services:
  - type: web
    name: hrms-lite-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn hrms.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hrms-lite-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://your-frontend-domain.vercel.app

databases:
  - name: hrms-lite-db
    plan: free
    databaseName: hrms_db
    user: hrms_user
